language: python

install:
  - pip install tox

services:
  - cassandra

env:
  - CODECOV_TOKEN="78fc939e-430c-44ee-9396-adde6b4504b0"

matrix:
  include:
    - python: 3.4
      env:
        - TOX_ENV=py34
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env:
        - TOX_ENV=py37

script: tox -e $TOX_ENV

branches:
  only:
    - master

after_success:
  - codecov